{
 "title": "AMTRON-NAME",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Verbrauch total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT \"wh\" FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME')",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Veränderung (Verbrauch) zum Vormonat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Verbrauch dieser Monat",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"wh\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() and time >= now() - 30d",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    {
     "alias": "Verbrauch letzter Monat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"wh\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() - 30d and time >= now() - 60d",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    { "expression": "A", "reducer": "sum", "type": "reduce" },
    { "expression": "B", "reducer": "sum", "type": "reduce" },
    { "expression": "($C - $D) / $D * 100", "type": "math" }
   ]
  },
  {
   "title": "Current status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "AMTRON-NAME_charge_data",
     "query": "SELECT \"act_pwr\" FROM \"AMTRON-NAME_charge_data\" WHERE (\"device_id\" = 'AMTRON-NAME')",
     "select": [
      [
       { "params": [ "act_pwr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Ladeleistung",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_data",
     "query": "SELECT mean(\"act_pwr\") FROM \"AMTRON-NAME_charge_data\" WHERE (\"device_id\" = 'AMTRON-NAME') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "act_pwr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Kosten total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "€",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"costs\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME')",
     "select": [
      [
       { "params": [ "costs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Veränderung (Kosten) zum Vormonat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Kosten dieser Monat",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"costs\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() and time >= now() - 30d",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    {
     "alias": "Kosten letzter Monat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"costs\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() - 30d and time >= now() - 60d",
     "select": [
      [
       { "params": [ "costs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    { "expression": "A", "reducer": "sum", "type": "reduce" },
    { "expression": "B", "reducer": "sum", "type": "reduce" },
    { "expression": "($C - $D) / $D * 100", "type": "math" }
   ]
  },
  {
   "title": "Anzahl Ladevorgänge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT count(\"wh\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME')",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Ladezeit gesamt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"duration\")  / 3600 FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME')",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Veränderung (Ladezeit) zum Vormonat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"duration\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() and time >= now() - 30d",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT sum(\"duration\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') AND time <= now() - 30d and time >= now() - 60d",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    { "expression": "A", "reducer": "sum", "type": "reduce" },
    { "expression": "B", "reducer": "sum", "type": "reduce" },
    { "expression": "($C - $D) / $D * 100", "type": "math" }
   ]
  },
  {
   "title": "Ladevorgänge pro Monat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "alias": "Ladevorgänge",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT count(\"wh\") FROM \"AMTRON-NAME_charge_records\" WHERE (\"device_id\" = 'AMTRON-NAME') GROUP BY time(1m) fill(none)",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  },
  {
   "title": "Ladevorgänge & Ladedauer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "€",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "query": "SELECT mean(\"costs\") FROM \"AMTRON-NAME\" WHERE (\"device_id\" = 'AMTRON-NAME') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "costs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    },
    {
     "alias": "kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AMTRON-NAME_charge_records",
     "select": [
      [
       { "params": [ "wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "AMTRON-NAME" }
     ]
    }
   ]
  }
 ]
}